INSERT INTO drills (name, description, skill_area, target_issue, difficulty, equipment, age_min, age_max, duration_minutes, video_url, variations) VALUES
('Shadow Batting Footwork',
 'Player practises front foot press and back foot transfer movements against a row of cones, with no ball involved. Focus on stable head position and smooth weight transfer.',
 'BATTING', 'FOOTWORK', 'BEGINNER', 'cones', 8, 17, 10, NULL,
 'Add a feeder calling out front or back to react to.'),
('Tee Batting for Bat Path',
 'Hit balls off a stationary tee, focusing on a straight bat path through the line of the ball. Coach watches from behind to check the swing arc and follow-through.',
 'BATTING', 'BAT_PATH', 'BEGINNER', 'batting tee,balls', 8, 17, 15, NULL,
 'Move the tee to different heights and lateral positions to challenge balance.'),
('Drop Ball Timing',
 'Coach drops a ball from head height; the batter must time the hit at the top of the bounce, neither too early nor too late. Focus on quiet head and timing rather than power.',
 'BATTING', 'TIMING', 'INTERMEDIATE', 'balls,bat', 11, 17, 15, NULL,
 'Vary drop height to challenge the batter''s judgement.'),
('Short Ball Pull Shot',
 'Feeder delivers short balls; the batter must decide between pulling and leaving. Develops judgement on what to attack and what to duck under.',
 'BATTING', 'SHOT_SELECTION', 'INTERMEDIATE', 'balls,bat,helmet', 13, 17, 20, NULL,
 'Mix in good-length deliveries so the batter cannot pre-commit.'),
('Front Foot Defence Wall Drill',
 'Batter plays front foot defence repeatedly against a wall or rebounder, focusing on a stable base and the bat coming down straight.',
 'BATTING', 'STANCE', 'BEGINNER', 'bat,rebounder', 8, 17, 10, NULL,
 'If no rebounder is available, use a soft ball off a brick wall.'),
('Throwdown Driving',
 'Coach throws half volleys; the batter drives through the line on the front foot into target cones at mid-on and cover. Emphasis on full extension and follow-through.',
 'BATTING', 'BAT_PATH', 'INTERMEDIATE', 'balls,bat,cones', 11, 17, 20, NULL,
 'Vary the line so the batter must move the feet rather than reach.'),
('Bobble Feed Reactions',
 'Two feeders alternate rapid throws from short range; the batter must adjust timing on each delivery without resetting. Builds reaction speed and lighter footwork.',
 'BATTING', 'TIMING', 'ADVANCED', 'balls,bat', 13, 18, 15, NULL,
 'Limit each rep to twenty balls to keep quality high.'),
('Stance and Guard Setup',
 'Coach checks and corrects each player''s grip, stance width, backlift position, and head position. Use markers at the crease to standardise guard.',
 'BATTING', 'STANCE', 'BEGINNER', 'bat,stumps', 8, 17, 10, NULL,
 'Photograph or video each player for self-review.'),
('Spin Bowling Footwork',
 'Batter faces a spinner in the nets, focusing on using the feet — coming down the pitch to drive or going deep in the crease to cut. Emphasis on reading length early.',
 'BATTING', 'FOOTWORK', 'ADVANCED', 'balls,bat,net', 13, 18, 20, NULL,
 'Reward intent: every ball must commit forward or back.'),
('Scenario Shot Selection',
 'Coach calls out match situations (last over, eight needed; twenty off thirty with four wickets in hand) and the batter must pick appropriate shots from the next over of throwdowns.',
 'BATTING', 'SHOT_SELECTION', 'ADVANCED', 'balls,bat', 14, 18, 25, NULL,
 'Review each over together: was the right shot played for the situation?'),
('Target Bowling (Line)',
 'Place a target cone on a good length outside off stump. Bowler aims to hit it eight times out of ten, with a coach tracking the score.',
 'BOWLING', 'LINE', 'BEGINNER', 'balls,target cone,stumps', 8, 17, 15, NULL,
 'Move the target wider or fuller as accuracy improves.'),
('Run Up Rhythm Drill',
 'Bowler runs in without delivering a ball, focusing on consistent run-up length and rhythm to the crease. Mark each step with tape on the first run, then repeat without looking.',
 'BOWLING', 'ACTION', 'BEGINNER', 'marking tape', 8, 17, 10, NULL,
 'The goal is repeatable foot placement at the crease.'),
('Length Control Zones',
 'Mark three zones on the pitch (full, good, short). Coach calls a zone; the bowler must land the ball in it. Track success rate over eighteen deliveries.',
 'BOWLING', 'LENGTH', 'INTERMEDIATE', 'balls,cones,stumps', 11, 17, 20, NULL,
 'Reduce the call-to-delivery time as the session progresses to add pressure.'),
('Slower Ball Variations',
 'Practise the back-of-hand slower ball, the off-cutter, and the knuckle ball. Five deliveries of each, with a coach watching grip and release.',
 'BOWLING', 'VARIATIONS', 'ADVANCED', 'balls,stumps', 14, 18, 20, NULL,
 'Batter optional — sometimes blind net work is better for grip confidence.'),
('Seam Position Drill',
 'Bowler delivers focusing purely on presenting the seam upright at release. Coach watches from front-on with a slow-motion camera or phone.',
 'BOWLING', 'CONTROL', 'INTERMEDIATE', 'balls,stumps', 13, 17, 15, NULL,
 'Review each delivery: was the seam scrambled or upright?'),
('Yorker Practice',
 'Target the base of the stumps or the blockhole, often marked with a shoe or cone. Track accuracy over thirty balls.',
 'BOWLING', 'LENGTH', 'ADVANCED', 'balls,stumps,target', 14, 18, 15, NULL,
 'Batter optional — the target tells the truth.'),
('Bowling to a Field',
 'Set a field with cones; bowler must execute a specific plan — outside off with a slip cordon, or hard length with a leg-side trap. Coach reviews after each over.',
 'BOWLING', 'CONTROL', 'ADVANCED', 'balls,stumps,cones', 14, 18, 25, NULL,
 'Develops the link between intent, field, and execution.'),
('Bound and Delivery Stride',
 'Isolate the bound and delivery stride without a full run-up. From a standing start two paces back, bowler steps through, focusing on front-arm drive and hip rotation.',
 'BOWLING', 'ACTION', 'BEGINNER', 'balls', 8, 17, 10, NULL,
 'A partner can hold the front arm pre-delivery to exaggerate the position.'),
('Cross-Seam Bowling',
 'Practise the cross-seam delivery to encourage variable bounce. Useful on used pitches. Bowler grips across the seam and tries to land the ball flat-side down.',
 'BOWLING', 'VARIATIONS', 'INTERMEDIATE', 'balls,stumps', 13, 17, 15, NULL,
 'Goal: differentiate carry between successive deliveries.'),
('Accuracy Under Fatigue',
 'Bowler does a short fitness drill — six shuttle runs between cones — then immediately bowls six balls at a target. Repeat for five sets.',
 'BOWLING', 'LINE', 'ADVANCED', 'balls,stumps,cones', 14, 18, 20, NULL,
 'Simulates the end-of-spell drop in concentration. Track accuracy per set.'),
('High Catch Confidence',
 'Coach hits high catches with increasing difficulty, starting comfortable and progressing to over-the-shoulder retreating catches. Focus on calling, getting under the ball, and soft hands.',
 'FIELDING', 'CATCHING', 'BEGINNER', 'bat,balls', 8, 17, 15, NULL,
 'Use a tennis ball for first reps if needed to build confidence.'),
('Flat Catch Reactions',
 'Use a slip catching cradle, or coach edges from close range with a bat. Player practises low, fast catches from a relaxed crouch position.',
 'FIELDING', 'CATCHING', 'INTERMEDIATE', 'catching cradle', 11, 17, 15, NULL,
 'Emphasise watching the ball into the hands rather than reaching.'),
('Ground Fielding and Throw',
 'Player fields a rolled or hit ball on the run, picks it up cleanly, and throws at a single stump. Track hits out of twenty attempts.',
 'FIELDING', 'THROWING', 'BEGINNER', 'balls,single stump', 8, 17, 15, NULL,
 'Progress from straight throws to off-balance throws as accuracy improves.'),
('Relay Throwing',
 'Groups of three practise relay throws from the boundary to the keeper, with a relay fielder in between. Focus on flat, accurate throws hitting the relay fielder above the stumps.',
 'FIELDING', 'THROWING', 'INTERMEDIATE', 'balls,cones', 11, 17, 20, NULL,
 'Time the full relay and aim to beat it.'),
('Fielding Positioning Game',
 'Coach calls different match situations (left-hander on strike, leg spinner bowling, batter on ninety-five). Fielders must move to correct positions without verbal coaching.',
 'FIELDING', 'POSITIONING', 'ADVANCED', 'cones', 13, 18, 20, NULL,
 'Use a whiteboard with field diagrams.'),
('Calling and Running Between Wickets',
 'Pairs of batters practise running between the wickets, calling yes, no, or wait on every ball. Coach deliberately creates tight singles and twos to force communication.',
 'MATCH_AWARENESS', 'COMMUNICATION', 'BEGINNER', 'bat,balls,stumps', 8, 17, 15, NULL,
 'Non-striker calls first; striker can override.'),
('Pressure Scenario Simulation',
 'Set up a match scenario: ten runs needed off twelve balls, last pair at the crease. Batter must execute under realistic pressure with full fielders and a bowler.',
 'MATCH_AWARENESS', 'PRESSURE_RESPONSE', 'ADVANCED', 'bat,balls,stumps,cones', 14, 18, 25, NULL,
 'Replay if the team chases successfully or fails — review the decisions.'),
('Field Placement Decision Making',
 'Captain or aspiring captain sets fields for different match scenarios. Coach reviews the logic — why third slip rather than gully, why a long-on but no long-off.',
 'MATCH_AWARENESS', 'DECISION_MAKING', 'INTERMEDIATE', 'cones,whiteboard', 13, 17, 20, NULL,
 'Use a whiteboard with field diagrams.'),
('Between Overs Communication',
 'Practise the between-overs routine — bowler and captain discuss the plan, agree on the field, and reset. Role-play with feedback from the coach.',
 'MATCH_AWARENESS', 'COMMUNICATION', 'INTERMEDIATE', NULL, 11, 17, 10, NULL,
 'Good communication is a habit, not a happy accident.'),
('Game Situation Awareness',
 'Mid-match freeze: coach stops play during a practice game and quizzes players. What is the score? How many overs left? What is the plan with this batter? Builds situational thinking.',
 'MATCH_AWARENESS', 'DECISION_MAKING', 'ADVANCED', NULL, 13, 18, 20, NULL,
 'Answer aloud, no hesitation.');
